### ISSUE TITLE
Fill Obama Placeholder

### ISSUE THREAD

**Issue by maryamgunja** [unitedstates/images#14]
http://www.askthem.io/people/52ec1a78ec8d83e492000003

**Comment by konklone** [comment]
That'd be up to @walter and @davidmooreppf, I think.

**Comment by walter** [comment]
Some background about why @konklone kicked this back to AskThem.io. Unlike the senate and congress images, which we source from this repository, AskThem.io pulls in Barack Obama via his Twitter account (i.e. he, for various reasons, is treated as a "public figure" rather than an elected official).

This repository is a discreet project from AskThem.io that in some circumstances AskThem.io uses to provide images of officials, mostly the house and the senate.

@maryamgunja in other words, if an image is missing from AskThem.io it does not necessarily mean that it is missing from this repository or that it should be included in this repository.

If it exists here, but is not pulled into AskThem, open an issue in the askthem project.

If it does not exist here (and it makes sense for this project to include it), then open an issue here. In some circumstances you may also need to open an issue for AskThem to get everything wired together.

Hope that helps.

**Comment by konklone** [comment]
Thanks for the extra context, @walter! Didn't mean to come across as terse or anything.
