### ISSUE TITLE
Missing images: B001288

### ISSUE THREAD

**Issue by cburgos** [unitedstates/images#8]
It seems that the image for Cory Booker - B001288 is missing.

**Comment by konklone** [comment]
Yeah, I think it's just not available yet - it doesn't appear on GPO or [on the Bioguide](http://bioguide.congress.gov/scripts/biodisplay.pl?index=B001288). We'll accept submissions from other sources if [a few criteria are met](https://github.com/unitedstates/images#contributing-other-photos).

**Comment by hugovk** [comment]
Same goes for John Walsh (W000818).

**Comment by konklone** [comment]
And J000296, updated issue title.

**Comment by hugovk** [comment]
@konklone J000296 David W. Jolly has already been added in https://github.com/unitedstates/images/commit/2fc6cc8d25f49b0714b820267436375aa8c26128

Is it not showing up properly?

**Comment by konklone** [comment]
Whooooops, I tested the wrong URL. Removed from description, sorry for the disturbance.

**Comment by jnschrag** [comment]
Can we get an update for W000818? It seems he's up on BioGuide now: http://bioguide.congress.gov/scripts/biodisplay.pl?index=W000818

**Comment by hugovk** [comment]
I just gave it a quick run but it didn't pick up John Walsh W000818. It might be because W000818 isn't in https://github.com/unitedstates/congress-legislators/blob/master/legislators-current.yaml.

Output: http://pastebin.com/jqUBztFS

**Comment by rshorey** [comment]
John Walsh lost his election, so should no longer be in legislators-current.

**Comment by hugovk** [comment]
How about Cory A. Booker B001288?

**Comment by rshorey** [comment]
He won his election and is in current-legislators.yaml.

**Comment by hugovk** [comment]
Hmm, so B001288 is there https://github.com/unitedstates/congress-legislators/blob/master/legislators-current.yaml#L37093

And we don't already have the image in  https://github.com/unitedstates/images/tree/gh-pages/congress/original

But it's not showing in the script output: http://pastebin.com/jqUBztFS

That's probably because by default it looks for the 113th congress. But running for the 114th returns no links. I've created a new issue for this: https://github.com/unitedstates/images/issues/22

**Comment by hugovk** [comment]
See #25.

**Comment by hugovk** [comment]
This can be closed when https://github.com/unitedstates/images/pull/39 is merged.
